In [1]:
import pandas as pd
import requests

In [4]:
response =requests.get('https://api.themoviedb.org/3/trending/movie/day?api_key=c0b9257539cd62a65fe724f7745e46a9&language=en-US&page=1')

In [15]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','release_date','popularity','vote_average','vote_count']]

In [16]:
temp_df.head()

,id,title,release_date,popularity,vote_average,vote_count
0,1304313,Lee Cronin's The Mummy,2026-04-15,157.9774,7.070,287
1,931285,Mortal Kombat II,2026-05-06,146.0172,6.976,208
2,1439930,The Punisher: One Last Kill,2026-05-12,671.0993,8.550,906
3,687163,Project Hail Mary,2026-03-15,447.7858,8.595,3603
4,1242332,Normal,2026-04-16,12.3489,7.000,31

In [18]:
df = pd.DataFrame()

In [19]:
df

Empty DataFrame
Columns: []
Index: []

In [21]:
for i in range(1,501):
    response =requests.get('https://api.themoviedb.org/3/trending/movie/day?api_key=c0b9257539cd62a65fe724f7745e46a9&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [22]:
df

,id,title,release_date,popularity,vote_average,vote_count
0,1304313,Lee Cronin's The Mummy,2026-04-15,157.9774,7.100,288
1,931285,Mortal Kombat II,2026-05-06,146.0172,6.976,208
2,687163,Project Hail Mary,2026-03-15,447.7858,8.595,3604
3,1439930,The Punisher: One Last Kill,2026-05-12,671.0993,8.550,906
4,1242332,Normal,2026-04-16,12.3489,7.000,31
...,...,...,...,...,...,...
9989,699071,My Mother's Friend,2018-05-17,2.1241,6.500,4
9990,670435,Female Teacher Diary: Forbidden Sex,1995-09-08,24.2961,4.800,6
9991,639720,IF,2024-05-08,9.1823,6.966,1599
9992,627725,The Banker,2020-03-06,3.7374,7.618,1106
9993,618851,Pretty Guardian Sailor Moon Eternal the Movie ...,2021-01-08,2.7353,7.879,194

In [24]:
df.shape

(9994, 6)

In [25]:
df.to_csv('movies.csv')

# Well Done!